### ISSUE TITLE
Environment installation error

### ISSUE THREAD

**Issue by Phil9S** [Phil9S/swgs-absolutecn#17]
Conda environment fails to install and times out using the `install_env.sh` script.

**Comment by davidhemp** [comment]
Just wondering if there is a solution to this. I tried removing the version limits and was able to build the environment but the shipped version of QDNAseqmod was built with R version 3.4 and so incompatible. Can we rebuild it for v4.0 or newer?

[install_env] Package Biobase is installed.
[install_env] Package dplyr is installed.
[install_env] Package tidyverse is installed.
[install_env] Package QDNAseq is installed.
[install_env] Package QDNAseqmod is installed.
[install_env] Package doMC is installed.
[install_env] Package foreach is installed.
[install_env] Package ggplot2 is installed.
[install_env] Package stringr is installed.
[install_env] Package matrixStats is installed.
[install_env] Package parallel is installed.
[install_env] Package plyr is installed.
Error: package or namespace load failed for ‘QDNAseqmod’:
 package ‘QDNAseqmod’ was installed before R 4.0.0: please re-install it

**Comment by davidhemp** [comment]
Ah just noticed the other issue. The following worked.

conda env create -f config/conda.yaml
conda activate swgs-abscn
R> install.packages("remotes")
R> remotes::install_github('https://github.com/markowetzlab/QDNAseqmod')
