### ISSUE TITLE
Error executing pipeline

### ISSUE THREAD

**Issue by ehayes-icl** [Phil9S/swgs-absolutecn#20]
When submitting the dry-run from Step 5 Stage 1 I receive multiple errors.

It seems to be having problems creating the bam.ok file, or issues detecting it. Below are some of the errors I receive. Please can I get some advice on what may be causing this error? Thank you in advance.

--------------------------------------------------------------------------------------------------------------------------------
input: /rds/general/project/ettpstt/live/sWGS_profiling_test/bams_from_hg19/output_test/1_sample_test/PSTT10.bam
    output: /rds/general/project/ettpstt/live/sWGS_profiling_test/bams_from_hg19/output_test/1_sample_test/out/sWGS_fitting/ettpstt_100kb/bam.ok
    jobid: 5
    **reason: Missing output files: /rds/general/project/ettpstt/live/sWGS_profiling_test/bams_from_hg19/output_test/1_sample_test/out/sWGS_fitting/ettpstt_100kb/bam.ok**

rule sym_link:
    input: /rds/general/project/ettpstt/live/sWGS_profiling_test/bams_from_hg19/output_test/1_sample_test/PSTT10.bam, /rds/general/project/ettpstt/live/sWGS_profiling_test/bams_from_hg19/output_test/1_sample_test/out/sWGS_fitting/ettpstt_100kb/bam.ok
    output: /rds/general/project/ettpstt/live/sWGS_profiling_test/bams_from_hg19/output_test/1_sample_test/out/sWGS_fitting/ettpstt_100kb/bams/PSTT10.bam
    jobid: 4
    **reason: Missing output files: /rds/general/project/ettpstt/live/sWGS_profiling_test/bams_from_hg19/output_test/1_sample_test/out/sWGS_fitting/ettpstt_100kb/bams/PSTT10.bam; Input files updated by another job: /rds/general/project/ettpstt/live/sWGS_profiling_test/bams_from_hg19/output_test/1_sample_test/out/sWGS_fitting/ettpstt_100kb/bam.ok**

**Comment by TBradley27** [comment]
Hi @ehayes-icl,

I am not sure if these are errors. This looks like the expected output from a dry-run.

Have you tried running the command without using the `-n` flag?

**Comment by ehayes-icl** [comment]
Hi, 
Thanks for your reply. You were right, this does seem to have worked outside of dry run mode. 
Many thanks!
