### ISSUE TITLE
How to cite use of this tool in publications?

### ISSUE THREAD

**Issue by TBradley27** [Phil9S/swgs-absolutecn#21]
Hi Phil,

I was just wondering how you would prefer this tool to be cited when using in publications/presentations etc. ?

Cheers,
Thomas

**Comment by Phil9S** [comment]
Hi Thomas,

I guess the easiest way would be to cite our NComms paper? I have added a citation section to the README.md and I have also added a citable zenodo repository  [10.5281/zenodo.10040893](https://zenodo.org/doi/10.5281/zenodo.10040893).
